### ISSUE TITLE
Error in chain2paf

### ISSUE THREAD

**Issue by HFzzzzzzz** [AndreaGuarracino/chain2paf#5]
Hello, I have a problem when using chain2maf. I converted the chain file to the hal format. How should I solve this problem?

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src/main.rs:277:77
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
   3: chain2paf::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by AndreaGuarracino** [comment]
Hi @790634750, can you share your input or a part of it that triggers the error?

**Comment by HFzzzzzzz** [comment]
> Hi @790634750, can you share your input or a part of it that triggers the error?

https://drive.google.com/file/d/16yBB1dXl8Tr9pHPFzCbPCxmoUPICc02U/view?usp=drive_link          This result is obtained through **https://github.com/ComparativeGenomicsToolkit/hal/blob/chaining-doc/doc/chaining-mapping.md**

**Comment by AndreaGuarracino** [comment]
Thank you! The error was fixed in #6.
